export const storyParts = [
  { id: 1, text: 'You wake up in a mysterious forest...', options: [2, 3] },
  { id: 2, text: 'You see a house in the distance.', options: [4, 5] },
  { id: 3, text: 'You see a cave in the distance.', options: [6, 7] },
  {
    id: 4,
    text: 'You approach the house and knock on the door.',
    options: [8, 9],
  },
  {
    id: 5,
    text: 'You approach the house and open the door.',
    options: [10, 11],
  },
  { id: 6, text: 'You approach the cave and enter.', options: [12, 13] },
  { id: 7, text: 'You approach the cave and turn back.', options: [14, 15] },
  { id: 8, text: 'The door opens and a witch greets you.', options: [16, 17] },
  { id: 9, text: 'The door opens and a troll greets you.', options: [18, 19] },
  { id: 10, text: 'The house is empty.', options: [20, 21] },
  { id: 11, text: 'The house is empty.', options: [22, 23] },
  {
    id: 12,
    text: "The cave is dark and you can't see anything.",
    options: [24, 25],
  },
  {
    id: 13,
    text: "The cave is dark and you can't see anything.",
    options: [26, 27],
  },
  {
    id: 14,
    text: 'You turn back and see a wolf behind you.',
    options: [28, 29],
  },
  {
    id: 15,
    text: 'You turn back and see a wolf behind you.',
    options: [30, 31],
  },
  {
    id: 16,
    text: 'The witch invites you in and offers you a potion.',
    options: [32, 33],
  },
  {
    id: 17,
    text: 'The witch invites you in and offers you a potion.',
    options: [34, 35],
  },
  {
    id: 18,
    text: 'The troll invites you in and offers you a potion.',
    options: [36, 37],
  },
  {
    id: 19,
    text: 'The troll invites you in and offers you a potion.',
    options: [38, 39],
  },
  { id: 20, text: 'You drink the potion and die.', options: [] },
  {
    id: 21,
    text: 'You find a hidden room with a treasure chest.',
    options: [40, 41],
  },
  {
    id: 22,
    text: 'You hear a strange noise coming from upstairs.',
    options: [42, 43],
  },
  { id: 23, text: 'The house starts to shake.', options: [44, 45] },
  { id: 24, text: 'You find a torch and light it.', options: [46, 47] },
  {
    id: 25,
    text: 'You stumble and fall, finding a secret passage.',
    options: [48, 49],
  },
  {
    id: 26,
    text: 'You decide to explore deeper into the cave.',
    options: [50, 51],
  },
  {
    id: 27,
    text: 'You feel scared and decide to leave the cave.',
    options: [52, 53],
  },
  { id: 28, text: 'You try to run from the wolf.', options: [54, 55] },
  {
    id: 29,
    text: 'You stand your ground against the wolf.',
    options: [56, 57],
  },
  { id: 30, text: 'You climb a tree to escape the wolf.', options: [58, 59] },
  { id: 31, text: 'You find a stick to defend yourself.', options: [60, 61] },
  {
    id: 32,
    text: 'You drink the potion and gain super strength.',
    options: [62, 63],
  },
  { id: 33, text: 'You politely refuse the potion.', options: [64, 65] },
  { id: 34, text: 'You drink the potion and fall asleep.', options: [66, 67] },
  { id: 35, text: 'You throw the potion on the ground.', options: [68, 69] },
  {
    id: 36,
    text: 'You drink the potion and turn invisible.',
    options: [70, 71],
  },
  { id: 37, text: 'You swap the potion with water.', options: [72, 73] },
  { id: 38, text: 'You drink the potion and die.', options: [74, 75] },
  { id: 39, text: 'You pretend to drink the potion.', options: [76, 77] },
];
